<a href="https://colab.research.google.com/github/Anirudh9247/ML.23AG1A66D0/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
nl1=[1,2,3,4,5]
array1=np.array(nl1)
print(array1)

[1 2 3 4 5]


In [ ]:
#
array1=np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [ ]:
#2d array
array2=np.array([[1,2,3,7,8,9],[4,5,6,10,11,12]])
print(array2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#3d array
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3.dtype)

int64


In [ ]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3.dtype)

int64


In [ ]:
#dimension
print(array3.ndim)

3


In [ ]:
#shape
array4=np.array([[10,20,30]
                ,[40,50,60]])
print(array4.shape)
print(array4.nbytes)

(2, 3)
48


In [ ]:
#size
print(array4.size)

6


In [ ]:
array5=np.array([[1,2,3],[3,4,5]])
print(array5.shape)

(2, 3)
