In [2]:
import numpy as np

In [3]:
nl1=[1,2,3,4,5]
array1=np.array(nl1)
print(array1)

[1 2 3 4 5]


In [5]:
#
array1=np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [6]:
#2d array
array2=np.array([[1,2,3,7,8,9],[4,5,6,10,11,12]])
print(array2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [7]:
#3d array
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3.dtype)

int64


In [16]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3.dtype)

int64


In [17]:
#dimension
print(array3.ndim)

3


In [15]:
#shape
array4=np.array([[10,20,30]
                ,[40,50,60]])
print(array4.shape)
print(array4.nbytes)

(2, 3)
48


In [14]:
#size
print(array4.size)

6


In [20]:
array5=np.array([[1,2,3],[3,4,5]])
print(array5.shape)

(2, 3)
